# Generated by Django 3.1.2 on 2020-10-05 17:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('client_member_id', models.CharField(max_length=32)),
                ('account_id', models.CharField(max_length=32)),
            ],
        ),
    ]
