# Generated by Django 3.1.2 on 2020-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulseapi', '0002_auto_20201005_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
