# Generated by Django 3.1.2 on 2020-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpulseapi', '0003_auto_20201005_1937'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_id'), name='unique_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('client_member_id', 'account_id'), name='unique_member_id'),
        ),
    ]
